language: python
python:
    - "3.5"
install:
    pip install pytest coveralls pytest-cov
script:
    py.test --cov=easy_python_requirements --cov-report=term-missing --cov-report=html
after_success:
    coveralls
