language: python
python:
    - "3.5"
install:
    pip install pytest
    pip install coveralls
    pip install pytest-cov
script:
    py.test --cov=easy_python_requirements test
after_success:
    coveralls
